version: '3.8'
services:
  app:
    image: dev-and-deliver:latest
    ports:
      - '3000:3000'
    depends_on:
      - cache
    networks:
      - dev_and_deliver

  cache:
    image: mongo:latest
    container_name: mongo_cache
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: dev_and_deliver

networks:
  dev_and_deliver: